name: Module Builder

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Files
        working-directory: ./
        run: zip -r ./shadowrun6-lw.zip ./*

      - name: Get Version
        shell: bash
        id: get-version
        run: echo "::set-output name=version::$(node ./.github/workflows/get-version.js)"

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'main')
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{secrets.GITHUB_TOKEN}}
          artifacts: './shadowrun6-lw.zip,./system.json'
          tag: latest